version: '3.6'

services:

  jenkins:
    container_name: jenkins
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    privileged: true
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker

  registry:
    image: registry
    container_name: registry
    ports:
      - 5000:5000
    restart: always

  local-authorities-db:
    container_name: local-authorities-db
    build:
      context: ./local-authorities-db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=local_authorities_db
      - POSTGRES_INITDB_ARGS= --encoding=UTF-8
      - TZ=UTC
    ports:
      - 5433:5432
    restart: always

  local-authorities:
    container_name: local-authorities
    environment:
      - spring.datasource.url=jdbc:postgresql://local-authorities-db:5432/local_authorities_db
    image: com.diaxeirish-dhmwn/local-authorities:0.0.1-SNAPSHOT
    links:
      - local-authorities-db:database
    ports:
      - 3007:3007
    restart: always

  web-service:
    container_name: web-service
    build:
      context: ./web-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3006:3006
    volumes:
      - ./web-service:/usr/src/app/
      - ./web-service/node_modules